routes/admin.php
<?php
// Route::get('routes',[
// 	'as' => 'show.routes',
// 	'uses'=>'Admin\UserController@RouteList'
// ]);
// Route::get('/access-denied',function(){
//             return view('admin.permission_denied');
//         });

// Route::group(array('namespace'=>'Admin','prefix' => 'admin'), function () {

// 	Route::get('/admin', function(){
// 		return redirect()->route('admin.login.get');
// 	});

// 	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');

// 	Route::get('reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.admin');

// 	Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.reset');

// 	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login.get');

// 	Route::post('/login-post', 'Auth\AdminLoginController@login')->name('admin.login.post');

// 	Route::group(['middleware' => ['admin']], function () {
// 		Route::get('/locked',array(
// 	        'as'   => 'admin.locked',
// 	        'uses' => 'LockController@getlocked'
// 	    ));
// 		//route for dashboard
// 		Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');
// 		//route for logout
// 		Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
// 		//route for change-password
// 		Route::group(array('prefix' => 'user_masters','middleware' => ['admin','acl.permitted']), function () {
// 		Route::resource('roles','RoleController',['except'=>'destroy']);
// 		Route::get('role/status-change',[
// 					'as' => 'roles.status',
// 					'uses' => 'RoleController@changeStatus'
// 				]);
// 		Route::resource('users','UserController',['except'=>['destroy','show']]);
// 		Route::get('users/get-roles-name',[
// 					'as' => 'users.role.get.name',
// 					'uses' => 'UserController@getRoleName'
// 				]);
// 		Route::post('users/delete',[
// 			'as' => 'users.delete',
// 			'uses' => 'UserController@delete'
// 		]);
// 	});
// 	});
	
// });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.login.get');
});

Route::get('/admin', function(){
		return redirect()->route('admin.login.get');
	});

Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');

Route::get('reset/{token?}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('password.reset.admin');

Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('admin.password.reset');

Route::get('admin/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('admin.login.get');

Route::post('admin/login-post', 'Admin\Auth\AdminLoginController@login')->name('admin.login.post');

Route::group(array('middleware' => ['admin']), function () {
	Route::get('/locked',array(
        'as'   => 'admin.locked',
        'uses' => 'LockController@getlocked'
    ));
	//route for dashboard
	Route::get('admin/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
	//route for logout
	Route::get('admin/logout', 'Admin\Auth\AdminLoginController@logout')->name('admin.logout');
	
	Route::resource('admin/base_plate', 'Admin\BasePlateController',['except' => ['show']]);

	Route::resource('admin/beam', 'Admin\BeamController',['except' => ['show']]);

	Route::resource('admin/connector', 'Admin\ConnectorController',['except' => ['show']]);

	Route::resource('admin/bracing', 'Admin\BracingController',['except' => ['show']]);

	Route::get('admin/quotation','Admin\QuotationController@index')->name('quotation.index');
	Route::post('admin/quotation','Admin\QuotationController@store')->name('quotation.store');

	Route::get('admin/quotation/show','Admin\QuotationController@show')->name('quotation.show');
	Route::post('admin/quotation/show','Admin\QuotationController@generatePdf')->name('quotation.generate_pdf');

	Route::get('admin/myModalContent',function(){
		return view('admin.quotation.myModalContent');
	});
});

/*Route::get('admin/login',function(){
	return view('admin.login');
});
Route::get('admin/password-change',function(){
	return view('admin.email');
});
Route::get('admin/password-reset',function(){
	return view('admin.reset');
});
Route::get('admin/change-password',function(){
	return view('admin.changepassword');
});
Route::get('admin/dashboard',function(){
	return view('admin.dashboard');
});
Route::resource('admin/users', 'UserController',['except' => ['show']]);
Route::get('admin/dynamic-form',function(){
	return view('admin.dynamic-form.new');
});

Route::get('image/import',function(){
	return view('admin.image.index');
});
Route::get('admin/input',function(){
	return view('admin.input-type.index');
});
Route::get('/admin/input/form',function(){
	return view('admin.input-type.new');
});*/

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
   protected $fillable = [
        'firstname','lastname','email','address','department','salary', 'password','status','phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\AclPermission;
use Illuminate\Support\Facades\Route;
use App\Helpers\Utility;
use App\Models\Admin;
use App\Models\Role;
use App\Models\RolePermission;
use App\Models\UserPermission;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use Mail;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
     {
        if ($request->ajax()) {

                $where_str = '1 = ?';
                $where_params = [1];
                
                 if ($request->has('sSearch')) {
                    $search = $request->get('sSearch');
                    $where_str .= " and ( admins.name like \"%{$search}%\""
                    ."or admins.email like \"%{$search}%\""
                    ."or roles.name like \"%{$search}%\""
                    . ")";
                }

                $columns = array('admins.id','admins.name','admins.email','roles.name as role_name','admins.status','admins.updated_at');
                $data_count = Admin::select('id')
                                    ->Leftjoin('roles','roles.id','=','admins.role')
                                    ->where('is_vendor','0')
                                    ->whereRaw($where_str, $where_params)
                                    ->count();

                $data = Admin::select($columns)
                            ->Leftjoin('roles','roles.id','=','admins.role')
                            ->where('is_vendor','0')
                            ->whereRaw($where_str, $where_params);

               

                if ($request->has('iDisplayStart') && $request->get('iDisplayLength') != '-1') {
                    $data = $data->take($request->get('iDisplayLength'))->skip($request->get('iDisplayStart'));
                
                }
                
                if ($request->has('iSortCol_0')) {
                    for ($i = 0; $i < $request->get('iSortingCols'); $i++) {
                        $column = $columns[$request->get('iSortCol_' . $i)];
                        if (false !== ($index = strpos($column, ' as '))) {
                            $column = substr($column, 0, $index);
                        }
                        $data = $data->orderBy($column, $request->get('sSortDir_' . $i));
                    }
                }
                
                $data = $data->get()->toArray();
                
                $response['iTotalDisplayRecords'] = $data_count;
                $response['iTotalRecords'] = $data_count;

                $response['sEcho'] = intval($request->get('sEcho'));

                $response['aaData'] = $data;


                return $response;
            }

            return view('admin.users.index');
    }
 
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('name', 'id');
            // $role_list = ['' => 'Select Role'] + $role_list;
            return view('admin.users.new', compact('roles'));
    }
     public function store(UserRequest $request)
    {
        $name = $request->get('name');
        $email = $request->get('email');
        $role = $request->get('roles');
        $status = $request->get('status');
        $role_permission = $request->get('permission');
        
            $generate_password = Utility::getRandomCharString(8); 
            $password = bcrypt($generate_password);
            $user_save = new Admin();
            $user_save->name = $name;
            $user_save->email = $email;
            $user_save->password = $password;
            $user_save->role = $role;
            $user_save->status = $status;
            // dd($user_save);
            $user_save->save();
            $user_id = $user_save->id;
            // $current_permission_delete = UserPermissions::where('role_id',$role_id)->delete();
            $created_at = auth('admin')->user()->id;
            foreach ($role_permission as $key => $single_permission) {
                // print_r($single_permission);
                $route_name = AclPermission::select('route_name')->where('id',$single_permission)->get()->toArray();
                
                // echo "<pre>";print_r($route_name[0]['route_name']);
                // exit;
                $role_permission_save = new UserPermission();
                // echo "<pre>";
                // print_r($route_name);
                $role_permission_save->user_id = $user_id;
                $role_permission_save->permission_id = $single_permission;
                $role_permission_save->route_name = $route_name[0]['route_name'];
                $role_permission_save->created_by = $created_at;
                $role_permission_save->save();
            }
            // dd($user_save);
            // $subject = 'Your Login Credentials for Gizmojo';
            // $email_view = 'admin.send_password';
            Mail::send('admin.send_password', ['data' => $user_save,'password'=>$generate_password], function ($message) use ($user_save) {
                            $message->to('mk@gmail.com')->subject('Just one step to go');
                        });
            // $user = Admin::create($request->all());
            // $send_email_user = $this->dispatch(new SendMailJob($email_view,['name'=>$user_save->name,'email'=>$user_save->email,'password'=>$generate_password],$user_save->email,$subject));

            //  if ($request->save_button == 'save_new') {
            //     return back()->with('message', 'User added successfully')
            //         ->with('message_type', 'success');
            // }
            // return redirect()->route('users.index')
            //                 ->with('message','User Added successfully')
            //                 ->with('message_type','success');
            return response()->json(array('success' => true,'action'=>'added'),200);
    }

    public function getRoleName(Request $request){
        $id = $request->id;
       
            $role_current_permissions = RolePermission::where('role_id',$id)->pluck('permission_id')->toArray();
            $user_permission = AclPermission::getPermission();
            // dd($role_current_permissions);
            $get_html = view('admin.users.role', compact('role_current_permissions','user_permission'))->render();

            return response()->json(array('html'=>$get_html,'success' => true), 200);
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $user = Admin::findOrFail($id);
            $user_permission = AclPermission::getPermission();
            $roles = Role::pluck('name','id');
            // dd($user_permission);
            $role_current_permissions = UserPermission::where('user_id',$id)->pluck('permission_id')->toArray();

            return view('admin.users.edit',compact('user','roles','user_permission','role_current_permissions','id'));
    }
    public function show($id)
    {
       
    }
    public function update(Request $request)
    {
       $name = $request->get('name');
            $email = $request->get('email');
            $role = $request->get('roles');
            $status = $request->get('status');
            $role_permission = $request->get('permission');
            
            $user_save = Admin::findOrFail($request->id);
            $user_save->name = $name;
            $user_save->email = $email;
            $user_save->role = $role;
            $user_save->status = $status;

            $user_save->save();
            $user_id = $user_save->id;
            // dd($user_id);
            $current_permission_delete = UserPermission::where('user_id',$user_id)->delete();

            $created_at = auth('admin')->user()->id;
            foreach ($role_permission as $key => $single_permission) {
                // print_r($single_permission);
                $route_name = AclPermission::select('route_name')->where('id',$single_permission)->get()->toArray();
                
                // echo "<pre>";print_r($route_name[0]['route_name']);
                // exit;
                $role_permission_save = new UserPermission();
                // echo "<pre>";
                // print_r($route_name);
                $role_permission_save->user_id = $user_id;
                $role_permission_save->permission_id = $single_permission;
                $role_permission_save->route_name = $route_name[0]['route_name'];
                $role_permission_save->created_by = $created_at;
                $role_permission_save->updated_by = $created_at;
                $role_permission_save->save();
            }
            //dd($user);
            // $this->syncPermissions($request, $user);
            // $user->save();
             // return redirect()->route('users.index')
             //                ->with('message','User updated successfully')
             //                ->with('message_type','success');

            return response()->json(array('success' => true,'action'=>'updated'),200);
    }
    public function RouteList(){
            // $dd= Route::getCurrentRoute()->getActionName();
            $routes = Route::getRoutes();
            
            $route_array = [];
            foreach ($routes as $value) {
                $route = $value->getName();
                $log_viewer = explode('::', $route);
                
                $route_method = $value->methods[0]; //method
                $route_action = $value->getActionName(); //method
                $route_path = $value->uri();  //url
                $route_inner = explode('.', $route);
                $last_index = last($route_inner);

resources/views/admin/users/edit.blade.php
@extends('admin.layout.layout')
@section('style')
    <?= Html::style('backend/plugins/jquery-multi-select/css/multi-select.css',[],IS_SECURE) ?>
@stop
@section('start_form')
    <?=Form::model($user, ['method'=>'PATCH','id'=>'user_edit_form', 'class' => 'm-0 form-horizontal'])?>
@stop
@section('top_fixed_content')
<nav class="navbar navbar-static-top">
    <div class="title">
         <h4><?=Breadcrumbs::render('edit_user',$user) ?></h4>
    </div>
    <div class="pl-10">
        <button type="submit" name="save_button" value="save" id="save_exit_1" class="btn btn-primary btn-sm save save_exit" title="Save & Exit" ></i>Save</button>
        <a href="javascript;;" onclick="window.history.go(-1); return false;" class="btn btn-default btn-sm" title="Back to users page">Cancel</a>
    </div>
</nav>
@stop
@section('content')
@include('admin.users._form')
<div id="permission_add" class="row">
    <div class="row">
        @foreach($user_permission as $keys => $single_user_perms)
            <div class="col-md-4 p-10">
                <div class="card">
                    <h5 class="subtitle">
                        <?=  ucwords(str_replace('_',' > ', $keys)) ?>
                    </h5>
                    <hr>
                    <div class="animated-checkbox">
                        <label>
                            <input type="checkbox" class ="sub_selection" value="<?= $keys ?>"><span class="label-text">Select All</span>
                        </label>
                    </div>
                    <?= Form::select('permission[]',$single_user_perms,old('permission',$role_current_permissions), array('multiple'=>true,'class' => 'multi-select user_permission_multi '.$keys)) ?>
                </div>
            </div>
        @endforeach
    </div>
</div>

<div class="text-right">
   <button type="submit" name="save_button" value="save" id="save_exit_2" class="btn btn-primary btn-sm save save_exit" title="Save & Exit" ></i>Save</button>
    <a href="javascript;;" onclick="window.history.go(-1); return false;" class="btn btn-default btn-sm" title="Back to users page">Cancel</a>
</div>
@stop

@section('end_form')
<?=Form::close()?>
@stop
@section('script')
<?= Html::script('backend/js/select2.min.js',[],IS_SECURE) ?> 
<?= Html::script('backend/js/jquery.form.min.js',[],IS_SECURE) ?>
<?= Html::script('backend/plugins/jquery-multi-select/js/jquery.multi-select.js',[],IS_SECURE) ?>

    <script type="text/javascript">
        $('.select2').select2();

        $('.user_permission_multi').multiSelect();

        $('form').submit(function(){
            $('.overlay').show();
        });

        $("#selectall").click(function(){
            var is_checked = $(this).is(':checked');
            $(".sub_selection").prop('checked',is_checked);
            if (is_checked == true) {
                $('.user_permission_multi').multiSelect('select_all');
            }else{
                $('.user_permission_multi').multiSelect('deselect_all');
            }
        });

        $('.sub_selection').click(function(){
            var is_checked = $(this).is(':checked');
            var sub_selection_value = $(this).val();

            if (is_checked == true) {
                $('.'+sub_selection_value).multiSelect('select_all');
            }else{
                $('.'+sub_selection_value).multiSelect('deselect_all');
            }
        })

        $("input[type='checkbox'][class*='select_']").click(function(){
            var getClass = $(this).attr('class');
            var getSection = getClass.split(' ');
            var getSection = getSection[1].slice(7);
            var is_checked = $(this).is(':checked');
            $("."+getSection).prop('checked',is_checked);
        });


         //form submit 
        $(".save").click(function(e){
            var val = $(this).val();
            var method_type = 'PATCH';
            var id = '<?= $id?>';

            var url = "<?= URL::route('users.update',['id'=>':id']) ?>";
            url = url.replace(':id',id);

            var token = "<?=csrf_token()?>";
        
            $('#user_edit_form').ajaxSubmit({
                url: url,
                type: method_type,
                data: { "_token" : token,"id":id },
                dataType: 'json',
                
                beforeSubmit : function()
                {
                    if(val == 'save')
                    {
                        $('.save').attr('disabled',true);
                        $('.save').html('<i class="fa fa-spinner fa-spin"></i> Please wait...');
                    }
                    $("[id$='_error']").empty();
                },
                
                success : function(resp)
                {              
                    $(".overlay").hide();
                    
                    if (resp.success == true) {
                        var  action = resp.action;
                        toastr.success('User successfully '+action);

                        if(val == 'save')
                        {
                            $('.save').attr('disabled',true);
                            $('.save').html('<i class="fa fa-spinner fa-spin"></i> Please wait...');
                            window.location.href = "<?=route('users.index')?>";
                        }
                        else
                        {
                            $('.save').attr('disabled',true);
                            $('.save').html('<i class="fa fa-spinner fa-spin"></i> Please wait...');
                            window.location.href = "<?=route('users.index')?>";
                        }
                    }
                   
                },
                error : function(respObj){    
                    $.each(respObj.responseJSON.errors, function(k,v){
                        $('#'+k+'_error').text(v);
                    });
                    toastr.error('there were some errors!');
                        $('#save_exit_1').attr('disabled',false);
                        $('#save_exit_1').html('Save');
                        $('#save_exit_2').attr('disabled',false);
                        $('#save_exit_2').html('Save');
                    
                    $(".overlay").hide();
                }
            });
        });

        // role change
        $('#role').change(function(){
            var val = $(this).val();
            var url = "<?= URL::route('users.role.get.name')?>";
            var method_type = 'GET';
            var token = "<?=csrf_token()?>";
            // console.log(val);
            $.ajax({
                type:method_type,
                url:url,
                data:{'id': val,'token': token},
                dataType:'json',
                success: function(respObj) {
                    if(respObj.success == true)
                    {
                        $('#permission_add').html(respObj.html);
                    }
                }
            });
        });
    </script>
    @include('admin.layout.alert')
@endsection

resources/views/admin/users/new.blade.php
@extends('admin.layout.layout')
@section('style')
    <?= Html::style('backend/plugins/jquery-multi-select/css/multi-select.css',[],IS_SECURE) ?>
@stop
@section('start_form')
    <form id="user_create_form" class="m-0 form-horizontal">
@stop
@section('top_fixed_content')
<nav class="navbar navbar-static-top">
    <div class="title">
        <h4><?=Breadcrumbs::render('create_user') ?></h4>
    </div>
    <div class="pl-10">
        <button type="submit" name="save_button" value="save_new" id="save_new_1" class="btn btn-primary btn-sm disabled-btn save" title="Save and add new">Save & Add New</button>
        <button type="submit" name="save_button" value="save_exit" id="save_exit_1" class="btn btn-primary btn-sm disabled-btn save" title="Save">Save</button>
        <a href="<?=URL::route('users.index')?>" class="btn btn-default btn-sm" title="Back to users Page">Cancel</a>
    </div>
</nav>
@stop
@section('content')
@include('admin.users._form')

<div id="permission_add" class="row"></div>

<div class="text-right">
   <button type="submit" name="save_button" value="save_new" id="save_new_2" class="btn btn-primary btn-sm disabled-btn save" title="Save & Add New user">Save & Add New</button>
    <button type="submit" name="save_button" value="save_exit" id="save_exit_2" class="btn btn-primary btn-sm disabled-btn save" title="Save">Save</button>
    <a href="<?=URL::route('users.index')?>" class="btn btn-default btn-sm" title="Back to user Page">Cancel</a>
</div>
@stop

@section('end_form')
</form>
@stop
@section('script')
 <?= Html::script('backend/js/jquery.form.min.js',[],IS_SECURE) ?>
  <?= Html::script('backend/plugins/jquery-multi-select/js/jquery.multi-select.js',[],IS_SECURE) ?>
    <?= Html::script('backend/js/select2.min.js',[],IS_SECURE) ?>
    <script type="text/javascript">
        $('.user_permission_multi').multiSelect();
        $('.user_permission_multi').multiSelect('deselect_all');

        $('form').submit(function(){
            $('.overlay').show();
        });

        $("#selectall").click(function(){
            var is_checked = $(this).is(':checked');
            $(".sub_selection").prop('checked',is_checked);
            if (is_checked == true) {
                $('.user_permission_multi').multiSelect('select_all');
            }else{
                $('.user_permission_multi').multiSelect('deselect_all');
            }
        });

        $('.sub_selection').click(function(){
            var is_checked = $(this).is(':checked');
            var sub_selection_value = $(this).val();

            if (is_checked == true) {
                $('.'+sub_selection_value).multiSelect('select_all');
            }else{
                $('.'+sub_selection_value).multiSelect('deselect_all');
            }
        })

        $("input[type='checkbox'][class*='select_']").click(function(){
            var getClass = $(this).attr('class');
            var getSection = getClass.split(' ');
            var getSection = getSection[1].slice(7);
            var is_checked = $(this).is(':checked');
            $("."+getSection).prop('checked',is_checked);
        });
    </script>
    <script type="text/javascript">
        $('.select2').select2();
        
        // user create
        $(".save").click(function(e){
            e.preventDefault();
            var val = $(this).val();
            var url = "<?= URL::route('users.store') ?>";
            var method_type = 'POST';
            var token = "<?=csrf_token()?>";
        
            $('#user_create_form').ajaxSubmit({
                url: url,
                type: method_type,
                data: { "_token" : token },
                dataType: 'json',
                
                beforeSubmit : function()
                {
                    if(val == 'save_new')
                    {
                        $('#save_new_1').attr('disabled',true);
                        $('#save_new_1').html('<i class="fa fa-spinner fa-spin"></i> Please wait...');
                        $('#save_new_2').attr('disabled',true);
                        $('#save_new_2').html('<i class="fa fa-spinner fa-spin"></i> Please wait...');
                    }
                    else
                    {
                        $('#save_exit_1').attr('disabled',true);
                        $('#save_exit_1').html('<i class="fa fa-spinner fa-spin"></i> Please wait...');
                        $('#save_exit_2').attr('disabled',true);
                        $('#save_exit_2').html('<i class="fa fa-spinner fa-spin"></i> Please wait...');
                    }
                    $("[id$='_error']").empty();
                },
                
                success : function(resp)
                {             
                console.log(val);     
                    $(".overlay").hide();
                    
                    if (resp.success == true) {
                        var  action = resp.action;
                        toastr.success('User successfully '+action);

                        if(val == 'save_new')
                        {
                            $('#save_new_1').attr('disabled',false);
                            $('#save_new_1').html('Save & Add New');
                            $('#save_new_2').attr('disabled',false);
                            $('#save_new_2').html('Save & Add New');
                            window.location.href = "<?=route('users.create')?>";
                        }
                        else
                        {
                            $('#save_exit_1').attr('disabled',false);
                            $('#save_exit_1').html('Save');
                            $('#save_exit_2').attr('disabled',false);
                            $('#save_exit_2').html('Save');
                            window.location.href = "<?=route('users.index')?>";
                        }
                    }
                   
                },
                error : function(respObj){    

                    $.each(respObj.responseJSON.errors, function(k,v){
                        $('#'+k+'_error').text(v);
                    });
                    toastr.error('there were some errors!');
                    if(val == 'save_new')
                    {
                        $('#save_new_1').attr('disabled',false);
                        $('#save_new_1').html('Save & Add New');
                        $('#save_new_2').attr('disabled',false);
                        $('#save_new_2').html('Save & Add New');
                    }
                    else
                    {
                        $('#save_exit_1').attr('disabled',false);
                        $('#save_exit_1').html('Save');
                        $('#save_exit_2').attr('disabled',false);
                        $('#save_exit_2').html('Save');
                    }
                    $(".overlay").hide();
                }
            });
        });

        $('#role').change(function(){
            var val = $(this).val();
            var url = "<?= URL::route('users.role.get.name')?>";
            var method_type = 'GET';
            var token = "<?=csrf_token()?>";
            console.log(url);
            $.ajax({
                type:method_type,
                url:url,
                data:{'id': val,'token': token},
                dataType:'json',
                success: function(respObj) {
                    if(respObj.success == true)
                    {
                        $('#permission_add').html(respObj.html);
                    }
                }
            });
        });

    </script>
    @include('admin.layout.alert')
@endsection