routes/admin.php
<?php
// Route::get('routes',[
// 	'as' => 'show.routes',
// 	'uses'=>'Admin\UserController@RouteList'
// ]);
// Route::get('/access-denied',function(){
//             return view('admin.permission_denied');
//         });

// Route::group(array('namespace'=>'Admin','prefix' => 'admin'), function () {

// 	Route::get('/admin', function(){
// 		return redirect()->route('admin.login.get');
// 	});

// 	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');

// 	Route::get('reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.admin');

// 	Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('admin.password.reset');

// 	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login.get');

// 	Route::post('/login-post', 'Auth\AdminLoginController@login')->name('admin.login.post');

// 	Route::group(['middleware' => ['admin']], function () {
// 		Route::get('/locked',array(
// 	        'as'   => 'admin.locked',
// 	        'uses' => 'LockController@getlocked'
// 	    ));
// 		//route for dashboard
// 		Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');
// 		//route for logout
// 		Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
// 		//route for change-password
// 		Route::group(array('prefix' => 'user_masters','middleware' => ['admin','acl.permitted']), function () {
// 		Route::resource('roles','RoleController',['except'=>'destroy']);
// 		Route::get('role/status-change',[
// 					'as' => 'roles.status',
// 					'uses' => 'RoleController@changeStatus'
// 				]);
// 		Route::resource('users','UserController',['except'=>['destroy','show']]);
// 		Route::get('users/get-roles-name',[
// 					'as' => 'users.role.get.name',
// 					'uses' => 'UserController@getRoleName'
// 				]);
// 		Route::post('users/delete',[
// 			'as' => 'users.delete',
// 			'uses' => 'UserController@delete'
// 		]);
// 	});
// 	});
	
// });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.login.get');
});

Route::get('/admin', function(){
		return redirect()->route('admin.login.get');
	});

Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email.admin');

Route::get('reset/{token?}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('password.reset.admin');

Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('admin.password.reset');

Route::get('admin/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('admin.login.get');

Route::post('admin/login-post', 'Admin\Auth\AdminLoginController@login')->name('admin.login.post');

Route::group(array('middleware' => ['admin']), function () {
	Route::get('/locked',array(
        'as'   => 'admin.locked',
        'uses' => 'LockController@getlocked'
    ));
	//route for dashboard
	Route::get('admin/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
	//route for logout
	Route::get('admin/logout', 'Admin\Auth\AdminLoginController@logout')->name('admin.logout');
	
	Route::resource('admin/base_plate', 'Admin\BasePlateController',['except' => ['show']]);

	Route::resource('admin/beam', 'Admin\BeamController',['except' => ['show']]);

	Route::resource('admin/connector', 'Admin\ConnectorController',['except' => ['show']]);

	Route::resource('admin/bracing', 'Admin\BracingController',['except' => ['show']]);

	Route::get('admin/quotation','Admin\QuotationController@index')->name('quotation.index');
	Route::post('admin/quotation','Admin\QuotationController@store')->name('quotation.store');

	Route::get('admin/quotation/show','Admin\QuotationController@show')->name('quotation.show');
	Route::post('admin/quotation/show','Admin\QuotationController@generatePdf')->name('quotation.generate_pdf');

	Route::get('admin/myModalContent',function(){
		return view('admin.quotation.myModalContent');
	});
});

/*Route::get('admin/login',function(){
	return view('admin.login');
});
Route::get('admin/password-change',function(){
	return view('admin.email');
});
Route::get('admin/password-reset',function(){
	return view('admin.reset');
});
Route::get('admin/change-password',function(){
	return view('admin.changepassword');
});
Route::get('admin/dashboard',function(){
	return view('admin.dashboard');
});
Route::resource('admin/users', 'UserController',['except' => ['show']]);
Route::get('admin/dynamic-form',function(){
	return view('admin.dynamic-form.new');
});

Route::get('image/import',function(){
	return view('admin.image.index');
});
Route::get('admin/input',function(){
	return view('admin.input-type.index');
});
Route::get('/admin/input/form',function(){
	return view('admin.input-type.new');
});*/

resources/views/admin/layout/alert.blade.php
@if(Session::has('message'))
	@if(Session::get('message_type'))
		<script>
	        $(document).ready(function(){
		        toastr.{{ Session::get('message_type') }}
		        ('{{ Session::get('message') }}');
	        });
	    </script>
    @endif
@endif

resources/views/admin/layout/breadcrumbs.blade.php
@if ($breadcrumbs)
    <ul class="breadcrumb p-0 m-0">
        @foreach ($breadcrumbs as $breadcrumb)
            @if(isset($breadcrumb->icon))
                {!! $breadcrumb->icon !!}
            @endif
            @if (!$loop->last)
                <li class="breadCrumbs_arrow"><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
            @else
                <li class="active">{{ $breadcrumb->title }}</li>
            @endif
        @endforeach
    </ul>
@endif

resources/views/admin/layout/footer.blade.php
<?=Html::script('backend/js/jquery.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/bootstrap.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/jquery.slimscroll.min.js', [], IS_SECURE)?>
<?=Html::script('backend/plugins/toastr-master/toastr.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/pace.min.js', [], IS_SECURE)?>
<?=Html::script('backend/js/main.js', [], IS_SECURE)?>
<?=Html::script('js/parsley.js', [], IS_SECURE)?>
<?= Html::script('backend/js/timeout.js',[],IS_SECURE) ?>

@yield('script')
<script type="text/javascript">
	@if(count($errors))
		toastr.error('Something went wrong please check');
	@endif
    $(document).ready(function(){

        $('#success').delay(3000).fadeOut('slow');
        $('#danger').delay(3000).fadeOut('slow');
        $('#warning').delay(3000).fadeOut('slow');

        @if(Request::is('admin*'))   
            var logout_url = "<?= URL::to('admin/logout') ?>";
            var redirUrl = '{{ URL::route("admin.locked") }}';
        @endif 
        // 1 sec = 1000 , wanrafter 2 hours 
        $.sessionTimeout({
            logoutUrl       : logout_url,
            redirUrl        : redirUrl,
            warnAfter       : 7200000,
            redirAfter      : 1200000,
            keepAlive       : false,
            countdownMessage: 'Otherwise You will be redirected to login page in {timer} seconds.',
            ignoreUserActivity: false
        });
    });
    $.ajaxSetup({
        statusCode: {
            401: function() {
                swal({
                   title: "Session Timeout",
                   type:"error",
                   timer: 2000,
                   showConfirmButton: false 
                });
                location.reload();
            }
        }
    });
</script>

resources/views/admin/layout/header.blade.php
<header class="main-header">
    <nav class="navbar navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="{{route('admin.dashboard')}}" class="navbar-brand"><img src="<?='/backend/images/kompressindia-weblogo.png'?>" alt=""></a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <i class="fa fa-bars"></i>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="@if(Request::segment(2) == 'quotation') active @endif"><a href="{{route('quotation.index')}}">Quotation</a></li>
                    <li class="@if(Request::segment(2) == 'base_plate') active @endif"><a href="{{route('base_plate.index')}}">Base Plate</a></li>
                    <li class="@if(Request::segment(2) == 'beam') active @endif"><a href="{{route('beam.index')}}">Beam</a></li>
                    <li class="@if(Request::segment(2) == 'connector') active @endif"><a href="{{route('connector.index')}}">Connector</a></li>
                    <li class="@if(Request::segment(2) == 'bracing') active @endif"><a href="{{route('bracing.index')}}">Bracing</a></li>
                    <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                        </ul>
                        </li> -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- User Account Menu -->
                    <li class="dropdown user user-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!-- hidden-xs hides the username on small devices so only the image appears. -->
                            <span class="hidden-xs"><i class="fa fa-user"></i> {{Auth::guard('admin')->user()->name}}</span>
                        </a>
                        <!-- <ul class="dropdown-menu" style="display: block;">
                            <li>
                            <a href="/admin/change-password" class="">Change Password</a>
                            </li>
                            <li>
                            <a href="http://erpproductsystem.local/admin/logout" class="">Logout</a>
                            </li>
                            </ul> -->
                        <ul class="dropdown-menu" style="width: 200px;box-shadow:0 0 10px rgba(0, 0, 0, 0.2);">
                            <li>
                                <a href="{{route('admin.logout')}}" class="">Sign out</a>
                            </li>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-custom-menu -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</header>

resources/views/admin/layout/layout.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#ffffff">
        <title>Admin</title>
        <!--  Css files  -->
        @include('admin.layout.web_header')
        @yield('style')
    </head>
    <body class="sidebar-mini fixed">
        <div class="wrapper">
            @yield('start_form')
            <!-- Header file -->
            @include('admin.layout.header')
            <!-- Side-Bar-->
            
            <!-- Content Start here -->
            <div class="content-wrapper">
                @yield('content')
            </div>
            <!-- Content End here -->
            <!-- footer contant -->
            @yield('end_form')
        </div>
        <!-- Js file -->
        @include('admin.layout.footer')
    </body>
</html>

resources/views/admin/layout/overlay.blade.php
<div class="overlay" style="display:none">
    <div class="m-loader mr-20"></div>
</div>

resources/views/admin/layout/sidebar.blade.php
<aside class="main-sidebar hidden-print">
    <section class="sidebar">
        <div class="search-panel">
            <div class="search-box">
              <div class="icon pull-left"><i class="fa fa-search"></i></div>
              <input class="text" type="text" placeholder="Special Search if require">
              <div class="clearfix"></div>
            </div>
        </div>
        <!-- Sidebar Menu-->
         <div class="sidebar-content">
            <ul class="sidebar-menu" id="nav-accordion">
                <ul class="sidebar-menu" id="nav-accordion">
                    <li class=" @if(Request::segment(2) == 'dashboard') active @endif">
                    <a href="/admin/dashboard">
                    <i class="fa fa-dashboard"></i>
                    <span>Dashboard</span>
                    </a>
                    </li>
                    @if(Request::is('admin*'))
                    @if(App\Helpers\RolePermissionCheck::isPermitted('roles.index') ||
                        App\Helpers\RolePermissionCheck::isPermitted('users.index'))
                    <li class="sub-menu @if(Request::segment(2) == 'user_masters') active @endif">
                        <a href="javascript:;">
                            <i class="fa fa-user"></i>
                            <span>User Master</span>
                            <i class="fa fa-angle-right"></i>
                        </a>
                        <ul class="treeview-menu @if(Request::segment(2) == 'user_masters' && (Request::segment(3) == 'roles')) menu-open @endif">
                        @if(App\Helpers\RolePermissionCheck::isPermitted('roles.index'))
                            <li>
                                <a href="<?=route('roles.index')?>" class="@if(Request::segment(3) == 'roles') active @endif">
                                    <i class="fa fa-pencil-square-o"></i>
                                    <span>Roles</span>
                                </a>
                            </li>
                        @endif
                        @if(App\Helpers\RolePermissionCheck::isPermitted('users.index'))
                            <li>
                                <a href="<?=route('users.index')?>" class="@if(Request::segment(3) == 'users') active @endif">
                                    <i class="fa fa-user"></i>
                                    <span>Users</span>
                                </a>
                            </li>
                        @endif
                        </ul>
                    </li>
                    @endif
                    @endif
                </ul>
                <li class="spacer"></li>
                <li class="logout"><a href="javascript:;"><i class="fa fa-user"></i>
                <span><?= auth('admin')->user()->name ?></span>
                <i class="fa fa-angle-right"></i></a>
                    <ul class="logout-modal">
                        <li><a href="/admin/change-password">Change Password</a></li>
                        <li><a href="<?= route('admin.logout') ?>"> Logout</a></li>
                    </ul>
                </li>
                
            </ul>
        </div>
    </section>
</aside>

resources/views/admin/layout/web_header.blade.php
<?=Html::style('backend/css/main.css')?>
<?=Html::style('backend/css/custom.css')?>
<?=Html::style('css/parsley.css')?>
<?=Html::style('backend/plugins/toastr-master/toastr.min.css')?>